/**
 * FinLen Smart Document Analyzer API service.
 *
 * Single documented endpoint: POST /api/v1/analyzer/documents
 * Auth (Bearer JWT), base URL, and HTTP error normalization are handled by
 * the shared `apiClient`. The multipart boundary is generated by the browser,
 * so Content-Type is intentionally never set manually.
 */
import { ApiError, apiClient } from "./client";
import type {
  AnalyzeDocumentResponse,
  DocumentAnalysis,
  FinancialLiteracyConcept,
  FinancialTerms,
  RiskFactor,
  RiskLevel,
  RiskSeverity,
} from "../types/analyzer";

const RISK_LEVELS: readonly RiskLevel[] = [
  "low",
  "medium",
  "high",
  "critical",
  "unknown",
];

const RISK_SEVERITIES: readonly RiskSeverity[] = [
  "low",
  "medium",
  "high",
  "critical",
];

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function readString(value: unknown, fallback = ""): string {
  return typeof value === "string" ? value : fallback;
}

function readNullableString(value: unknown): string | null {
  return typeof value === "string" && value.trim() !== "" ? value : null;
}

function readNullableNumber(value: unknown): number | null {
  if (typeof value === "number" && Number.isFinite(value)) return value;
  return null;
}

function readStringArray(value: unknown): string[] {
  if (!Array.isArray(value)) return [];
  return value
    .map((item) => readString(item).trim())
    .filter((item) => item.length > 0);
}

function readRiskLevel(value: unknown): RiskLevel {
  const raw = readString(value).toLowerCase().trim();
  return (RISK_LEVELS as readonly string[]).includes(raw)
    ? (raw as RiskLevel)
    : "unknown";
}

function readRiskSeverity(value: unknown): RiskSeverity {
  const raw = readString(value).toLowerCase().trim();
  return (RISK_SEVERITIES as readonly string[]).includes(raw)
    ? (raw as RiskSeverity)
    : "medium";
}

function readFinancialTerms(value: unknown): FinancialTerms {
  const source = isRecord(value) ? value : {};
  return {
    principal: readNullableNumber(source.principal),
    interest_rate: readNullableNumber(source.interest_rate),
    interest_period: readNullableString(source.interest_period),
    due_date: readNullableString(source.due_date),
    currency: readNullableString(source.currency),
  };
}

function readRiskFactors(value: unknown): RiskFactor[] {
  if (!Array.isArray(value)) return [];
  return value.filter(isRecord).map((item) => ({
    title: readString(item.title).trim(),
    description: readString(item.description).trim(),
    severity: readRiskSeverity(item.severity),
  }));
}

function readFinancialLiteracy(value: unknown): FinancialLiteracyConcept[] {
  if (!Array.isArray(value)) return [];
  return value.filter(isRecord).map((item) => ({
    concept: readString(item.concept).trim(),
    explanation: readString(item.explanation).trim(),
  }));
}

/**
 * Normalizes the backend payload without inventing data.
 * Missing optional values stay `null`, missing collections become empty arrays
 * so the UI can never crash on an incomplete AI response.
 */
function parseDocumentAnalysis(payload: unknown): DocumentAnalysis {
  const root = isRecord(payload) ? payload : {};
  const analysis = isRecord(root.analysis) ? root.analysis : {};

  return {
    document_type: readString(analysis.document_type).trim(),
    summary: readString(analysis.summary).trim(),
    financial_terms: readFinancialTerms(analysis.financial_terms),
    risk_level: readRiskLevel(analysis.risk_level),
    risk_factors: readRiskFactors(analysis.risk_factors),
    red_flags: readStringArray(analysis.red_flags),
    recommended_actions: readStringArray(analysis.recommended_actions),
    financial_literacy: readFinancialLiteracy(analysis.financial_literacy),
  };
}

/**
 * Uploads a financial document for stateless OCR + AI analysis.
 */
export async function analyzeDocument(
  file: File,
): Promise<AnalyzeDocumentResponse> {
  const formData = new FormData();
  formData.append("file", file);

  const payload = await apiClient<unknown>("/api/v1/analyzer/documents", {
    method: "POST",
    requiresAuth: true,
    body: formData,
  });

  return { analysis: parseDocumentAnalysis(payload) };
}

export interface AnalyzerErrorInfo {
  title: string;
  message: string;
  hint?: string;
  /** Retrying the exact same file has a realistic chance of succeeding. */
  canRetry: boolean;
  /** The user must re-authenticate before trying again. */
  requiresAuth: boolean;
}

/**
 * Maps analyzer HTTP failures onto the Indonesian copy defined for this feature.
 * Falls back to the shared client message when the status is not analyzer-specific.
 */
export function resolveAnalyzerErrorInfo(error: unknown): AnalyzerErrorInfo {
  if (!(error instanceof ApiError)) {
    return {
      title: "Analisis dokumen gagal",
      message: "Terjadi kendala yang tidak terduga. Silakan coba lagi.",
      canRetry: true,
      requiresAuth: false,
    };
  }

  const detail = (error.detail || "").toLowerCase();

  switch (error.status) {
    case 0:
      return {
        title: "Tidak dapat terhubung ke server",
        message: "Periksa koneksi internetmu dan coba lagi.",
        canRetry: true,
        requiresAuth: false,
      };
    case 400:
      return {
        title: "Format dokumen tidak didukung",
        message: "Gunakan PDF, JPG, atau PNG.",
        canRetry: false,
        requiresAuth: false,
      };
    case 401:
      return {
        title: "Sesi kamu sudah berakhir",
        message: "Silakan masuk kembali untuk melanjutkan.",
        canRetry: false,
        requiresAuth: true,
      };
    case 413:
      return {
        title: "Ukuran dokumen terlalu besar",
        message: "Maksimal ukuran file adalah 10 MB.",
        canRetry: false,
        requiresAuth: false,
      };
    case 422:
      return {
        title: "Teks dokumen tidak terbaca",
        message:
          "FinLen tidak menemukan teks yang dapat dibaca dari dokumen ini.",
        hint: "Coba gunakan dokumen dengan kualitas scan yang lebih jelas.",
        canRetry: false,
        requiresAuth: false,
      };
    case 502:
      if (detail.includes("ocr")) {
        return {
          title: "Layanan pembacaan dokumen terganggu",
          message:
            "Layanan pembacaan dokumen sedang mengalami gangguan. Coba lagi beberapa saat lagi.",
          canRetry: true,
          requiresAuth: false,
        };
      }
      if (detail.includes("invalid response")) {
        return {
          title: "Hasil analisis tidak dapat diproses",
          message: "Hasil analisis tidak dapat diproses. Silakan coba lagi.",
          canRetry: true,
          requiresAuth: false,
        };
      }
      return {
        title: "Layanan analisis terganggu",
        message:
          "Layanan analisis sedang mengalami gangguan. Coba lagi beberapa saat lagi.",
        canRetry: true,
        requiresAuth: false,
      };
    case 504:
      return {
        title: "Analisis terlalu lama",
        message: "Analisis membutuhkan waktu terlalu lama. Silakan coba lagi.",
        canRetry: true,
        requiresAuth: false,
      };
    default:
      return {
        title: "Analisis dokumen gagal",
        message: error.userMessage,
        canRetry: error.status >= 500,
        requiresAuth: false,
      };
  }
}
